@echo off

IF EXIST debug\task-1.exe (
    SET PROG=debug\task-1
) ELSE (
    IF EXIST x64\debug\task-1.exe (
    SET PROG=x64\debug\task-1
    )
)
::SET PROG=debug\task-1

:: TEST#1
SET OP=+
SET OP1=38
SET OP2=4
CALL :CHECK OP1 OP OP2
:: TEST#2
SET OP=-
SET /A OP1=%OP1%*2
SET /A OP2=%OP2%*%OP2%
CALL :CHECK OP1 OP OP2
:: TEST#3
SET OP=*
SET /A OP1=%OP1%-536
SET /A OP2=%OP2%/4
CALL :CHECK OP1 OP OP2
:: TEST#4
SET OP=/
SET /A OP1=%OP1%*3
SET /A OP2=%OP2%+67
CALL :CHECK OP1 OP OP2
:: TEST#5
SET OP=%%
SET /A OP1=%OP1%*2
SET /A OP2=%OP2%*%OP2%
CALL :CHECK OP1 OP OP2
:: TEST#6
SET OP="^"
SET OP1=2
SET OP2=13
SET ANS=8192
FOR /F %%i in ('%PROG% %OP1% %OP% %OP2%') DO SET RES=%%i
ECHO %OP1% ^^ %OP2% = %RES%
IF %RES% EQU %ANS% (ECHO PASSED) ELSE (ECHO WRONG)

PAUSE

:CHECK OP1 OP OP2
SET /A ANS=%OP1%%OP%%OP2%
FOR /F %%i in ('%PROG% %OP1% %OP% %OP2%') DO SET RES=%%i
ECHO %OP1% %OP% %OP2% = %RES%
IF %RES% EQU %ANS% (ECHO PASSED) ELSE (ECHO WRONG)
EXIT /B 0